services:
  - type: static
    name: SPA-Frontend

    repo: https://github.com/FaridMo99/SPA
    branch: main 

    buildCommand: npm run build
    staticPublishPath: ./dist
    
    routes:
      # internal rewrite for api
      - type: rewrite
        source: /api/*
        destination: https://SPA-Backend/$1
        
      # Spa routing since its only one file
      - type: rewrite
        source: /*
        destination: /index.html